# Generated by Django 4.2.3 on 2023-07-23 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inference', '0003_inferenceimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InferenceImage',
        ),
    ]
