# Generated by Django 4.2.3 on 2023-07-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inference', '0005_carrimtypebycategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrimtypebycategory',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
