# Generated by Django 4.2.3 on 2023-07-24 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inference', '0007_alter_carrimtypebycategory_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrimtypebycategory',
            options={'ordering': ['category']},
        ),
    ]
