# Generated by Django 4.2.3 on 2023-07-24 14:39

from django.db import migrations, models
import inference.models


class Migration(migrations.Migration):

    dependencies = [
        ('inference', '0008_alter_carrimtypebycategory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrimtypebycategory',
            options={},
        ),
        migrations.AlterField(
            model_name='carrimtypebycategory',
            name='image',
            field=models.ImageField(null=True, upload_to=inference.models.getImagePath),
        ),
    ]
